In [1]:
import pandas as pd
from sklearn import linear_model
import numpy as np

In [2]:
dataset = pd.read_csv('houseprice.csv')
dataset

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
dataset.Bedrooms


0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
Name: Bedrooms, dtype: float64

In [4]:
dataset.Bedrooms.median()
import math

In [5]:
Bedrooms_median = math.floor(dataset.Bedrooms.median())
Bedrooms_median


3

In [6]:
dataset.Bedrooms = dataset.Bedrooms.fillna(Bedrooms_median)


In [7]:
dataset

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
dataset.Bedrooms.fillna(Bedrooms_median)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: Bedrooms, dtype: float64

In [9]:
reg = linear_model.LinearRegression()

In [10]:
reg.fit(dataset[['Area','Bedrooms','Age']], dataset.Price)

LinearRegression()

In [11]:
reg.coef_


array([   137.25, -26025.  ,  -6825.  ])

In [12]:
reg.intercept_


383724.9999999998

In [13]:
reg.predict([[3000,3,40]])

array([444400.])

In [14]:
dataset

Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [15]:
y = dataset.iloc[:,3]
y

0    550000
1    565000
2    610000
3    595000
4    760000
Name: Price, dtype: int64

In [16]:
X = dataset.iloc[:,0:3]
X

Area  Bedrooms  Age
0  2600       3.0   20
1  3000       4.0   15
2  3200       3.0   18
3  3600       3.0   30
4  4000       5.0    8

In [17]:
X

Area  Bedrooms  Age
0  2600       3.0   20
1  3000       4.0   15
2  3200       3.0   18
3  3600       3.0   30
4  4000       5.0    8

In [18]:
y

0    550000
1    565000
2    610000
3    595000
4    760000
Name: Price, dtype: int64

In [19]:
regs = linear_model.LinearRegression()
regs.fit(X,y)

LinearRegression()

In [25]:
regs.predict([[3000,3,30]])

array([512650.])

In [36]:
import pickle

In [37]:
file = open('House_Price_Prediction.pkl','wb')
pickle.dump(regs,file)

In [38]:
House_Price_Prediction_Model = open('House_Price_Prediction.pkl', 'rb')
model = pickle.load(House_Price_Prediction_Model)